#!/bin/bash

# Get & use Prezto
git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"

setopt EXTENDED_GLOB
for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N); do
  ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
done

# Change default shell to zsh
chsh -s /bin/zsh

# Link my config files
rm -f ~/.zshrc ~/.zpreztorc
ln -s "${ZDOTDIR:-$HOME}"/LinuxConfig/.zshrc ~/.zshrc 
ln -s "${ZDOTDIR:-$HOME}"/LinuxConfig/.vimrc ~/.vimrc 
ln -s "${ZDOTDIR:-$HOME}"/LinuxConfig/.zpreztorc ~/.zpreztorc
ln -s "${ZDOTDIR:-$HOME}"/LinuxConfig/.dircolors ~/.dircolors

# Get current Solarized scheme
git clone git://github.com/altercation/vim-colors-solarized.git
mv vim-colors-solarized ~/.vim/bundle/

