#!/bin/zsh

# Get & use Prezto
git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"

setopt EXTENDED_GLOB
for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N); do
  ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
done

# Change default shell to zsh
chsh -s /bin/zsh

# Install up-to-date neovim (alternative would be Linux package from Github releases)
#
# On systems without FUSE (virtual machines etc.), it is possible to extract the appimage
# to a location of your choosing and editing the EDITOR variable in .zshrc, e.g.:
#   export EDITOR="~/LinuxConfig/squashfs-root/AppRun"
curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim.appimage --output-dir ~
chmod u+x ~/nvim.appimage

# Install tmux plugin manager
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

# Link my config files
rm -f ~/.zshrc ~/.zpreztorc
ln -s "${ZDOTDIR:-$HOME}"/LinuxConfig/.zshrc ~/.zshrc
ln -s "${ZDOTDIR:-$HOME}"/LinuxConfig/.zpreztorc ~/.zpreztorc
mkdir -p ~/.config/tmux/
ln -s "${ZDOTDIR:-$HOME}"/LinuxConfig/tmux.conf ~/.config/tmux/tmux.conf
ln -s "${ZDOTDIR:-$HOME}"/LinuxConfig/nvim ~/.config/nvim

# Remind to install the plugins
echo "Launch tmux and install downloaded plugins using combination '<Ctrl+Space> I'."
echo
echo "Launch nvim and run :MasonInstallAll command after lazy.nvim finishes downloading plugins."

